In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [3]:
class Net(nn.Module):
    def __init__(self): # 定义神经网络结构，输入数据 1x32x32
        super(Net, self).__init__()
        # 第一层（卷积层）
        self.conv1 = nn.Conv2d(1, 6, 3) # 输入频道 1、输出频道 6、卷积大小 3x3
        # 第二层（卷积层）
        self.conv2 = nn.Conv2d(6, 16, 3) # 输入频道 6，输出频道 16，卷积 3x3
        # 第三层（全连接层）
        self.fc1 = nn.Linear(16 * 28 * 28, 512) # 每次卷积后输入数据大小-2，输入维度 16x28z28，输出维度 512
        # 第四层（全连接层）
        self.fc2 = nn.Linear(512, 64) # 输入维度 512，输出维度 64
        # 第五层（全连接层）
        self.fc3 = nn.Linear(64, 2) # 输入维度 64，输出维度 2
        
    def forward(self, x): # 定义数据流向
        x = self.conv1(x)
        x = F.relu(x) # 固定 x 值的范围
        
        x = self.conv2(x)
        x = F.relu(x)
        
        x = x.view(-1, 16 * 28 * 28)
        x = self.fc1(x)
        x = F.relu(x)
        
        x = self.fc2(x)
        x = F.relu(x)
        
        x = self.fc3(x)
        
        return x

In [4]:
net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=12544, out_features=512, bias=True)
  (fc2): Linear(in_features=512, out_features=64, bias=True)
  (fc3): Linear(in_features=64, out_features=2, bias=True)
)


In [5]:
# 生成随机输入
input_data = torch.randn(1, 1, 32, 32)
print(input_data)
print(input_data.size())

tensor([[[[-0.1324, -0.7696, -1.6360,  ..., -0.5030, -0.8836,  0.0258],
          [-0.1568,  0.0994,  0.0134,  ...,  0.5536, -2.0184, -0.7458],
          [ 0.4117,  1.7976, -0.3961,  ...,  0.6498,  0.4854, -0.1478],
          ...,
          [-0.4134,  1.5046, -1.3173,  ..., -1.3056, -1.0549,  0.1810],
          [ 1.1652,  1.4554, -1.0699,  ...,  0.7821,  2.3261, -1.6988],
          [ 0.0214, -0.9995, -1.0826,  ..., -0.2065,  0.0740,  0.6086]]]])
torch.Size([1, 1, 32, 32])


In [6]:
# 运行神经网络
out = net(input_data)
print(out)
print(out.size())

tensor([[0.0595, 0.0476]], grad_fn=<AddmmBackward>)
torch.Size([1, 2])


In [7]:
# 随机生成真实值
target = torch.randn(2)
print(target)
target = target.view(1, -1) # -1 表示维度自动判断
print(target)

tensor([-0.4582, -1.7589])
tensor([[-0.4582, -1.7589]])


In [8]:
criterion = nn.L1Loss() # 定义损失函数，这里是绝对误差
loss = criterion(out, target) # 计算损失
print(loss)


tensor(1.1621, grad_fn=<L1LossBackward>)


In [9]:
# 反向传递
net.zero_grad() # 清零梯度
loss.backward() # 自动计算梯度、反向传递


In [10]:
# 更新权重
import torch.optim as optim

optimizer = optim.SGD(net.parameters(), lr = 0.01)
optimizer.step()

In [14]:
# 再次运行神经网络以及计算损失
out = net(input_data)
print(out)
print(out.size())


tensor([[0.0172, 0.0147]], grad_fn=<AddmmBackward>)
torch.Size([1, 2])


In [13]:
loss = criterion(out, target) # 计算损失
print(loss)

tensor(1.1245, grad_fn=<L1LossBackward>)
